//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.09 at 04:11:31 PM EET 
//


package ee.riik.xrd.dhl.producers.producer.dhl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ee.riik.xrd.dhl.producers.producer.dhl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ReceiveDocumentsResponse_QNAME = new QName("http://producers.dhl.xrd.riik.ee/producer/dhl", "receiveDocumentsResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ee.riik.xrd.dhl.producers.producer.dhl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendDocumentsV4ResponseTypeUnencoded }
     * 
     */
    public SendDocumentsV4ResponseTypeUnencoded createSendDocumentsV4ResponseTypeUnencoded() {
        return new SendDocumentsV4ResponseTypeUnencoded();
    }

    /**
     * Create an instance of {@link SendDocumentsV4RequestTypeUnencoded }
     * 
     */
    public SendDocumentsV4RequestTypeUnencoded createSendDocumentsV4RequestTypeUnencoded() {
        return new SendDocumentsV4RequestTypeUnencoded();
    }

    /**
     * Create an instance of {@link SendDocuments }
     * 
     */
    public SendDocuments createSendDocuments() {
        return new SendDocuments();
    }

    /**
     * Create an instance of {@link SendDocumentsV4RequestType }
     * 
     */
    public SendDocumentsV4RequestType createSendDocumentsV4RequestType() {
        return new SendDocumentsV4RequestType();
    }

    /**
     * Create an instance of {@link SendDocumentsResponse }
     * 
     */
    public SendDocumentsResponse createSendDocumentsResponse() {
        return new SendDocumentsResponse();
    }

    /**
     * Create an instance of {@link Base64BinaryType }
     * 
     */
    public Base64BinaryType createBase64BinaryType() {
        return new Base64BinaryType();
    }

    /**
     * Create an instance of {@link ReceiveDocuments }
     * 
     */
    public ReceiveDocuments createReceiveDocuments() {
        return new ReceiveDocuments();
    }

    /**
     * Create an instance of {@link ReceiveDocumentsV4RequestType }
     * 
     */
    public ReceiveDocumentsV4RequestType createReceiveDocumentsV4RequestType() {
        return new ReceiveDocumentsV4RequestType();
    }

    /**
     * Create an instance of {@link ReceiveDocumentsV4ResponseType }
     * 
     */
    public ReceiveDocumentsV4ResponseType createReceiveDocumentsV4ResponseType() {
        return new ReceiveDocumentsV4ResponseType();
    }

    /**
     * Create an instance of {@link SendingOptionArrayType }
     * 
     */
    public SendingOptionArrayType createSendingOptionArrayType() {
        return new SendingOptionArrayType();
    }

    /**
     * Create an instance of {@link DocumentRefsArrayType }
     * 
     */
    public DocumentRefsArrayType createDocumentRefsArrayType() {
        return new DocumentRefsArrayType();
    }

    /**
     * Create an instance of {@link SendDocumentsV4ResponseTypeUnencoded.Keha }
     * 
     */
    public SendDocumentsV4ResponseTypeUnencoded.Keha createSendDocumentsV4ResponseTypeUnencodedKeha() {
        return new SendDocumentsV4ResponseTypeUnencoded.Keha();
    }

    /**
     * Create an instance of {@link SendDocumentsV4RequestTypeUnencoded.Dokumendid }
     * 
     */
    public SendDocumentsV4RequestTypeUnencoded.Dokumendid createSendDocumentsV4RequestTypeUnencodedDokumendid() {
        return new SendDocumentsV4RequestTypeUnencoded.Dokumendid();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReceiveDocumentsV4ResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://producers.dhl.xrd.riik.ee/producer/dhl", name = "receiveDocumentsResponse")
    public JAXBElement<ReceiveDocumentsV4ResponseType> createReceiveDocumentsResponse(ReceiveDocumentsV4ResponseType value) {
        return new JAXBElement<ReceiveDocumentsV4ResponseType>(_ReceiveDocumentsResponse_QNAME, ReceiveDocumentsV4ResponseType.class, null, value);
    }

}
