//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.21 at 02:49:54 PM EEST 
//


package eu.x_road.xsd.xroad;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.x_road.xsd.identifiers.XRoadServiceIdentifierType;


/**
 * <p>Java class for CentralServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CentralServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serviceCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="implementingService" type="{http://x-road.eu/xsd/identifiers}XRoadServiceIdentifierType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CentralServiceType", propOrder = {
    "serviceCode",
    "implementingService"
})
public class CentralServiceType {

    @XmlElement(required = true)
    protected String serviceCode;
    protected XRoadServiceIdentifierType implementingService;

    /**
     * Gets the value of the serviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceCode(String value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the implementingService property.
     * 
     * @return
     *     possible object is
     *     {@link XRoadServiceIdentifierType }
     *     
     */
    public XRoadServiceIdentifierType getImplementingService() {
        return implementingService;
    }

    /**
     * Sets the value of the implementingService property.
     * 
     * @param value
     *     allowed object is
     *     {@link XRoadServiceIdentifierType }
     *     
     */
    public void setImplementingService(XRoadServiceIdentifierType value) {
        this.implementingService = value;
    }

}
