//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.29 at 02:39:43 PM EEST
//


package eu.x_road.xsd.xroad;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>
 * Java class for MemberType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MemberType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="memberClass" type="{http://x-road.eu/xsd/xroad.xsd}MemberClassType"/>
 *         &lt;element name="memberCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subsystem" type="{http://x-road.eu/xsd/xroad.xsd}SubsystemType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MemberType", propOrder = {"memberClass", "memberCode", "name", "subsystem"})
public class MemberType {

  @XmlElement(required = true)
  protected MemberClassType memberClass;
  @XmlElement(required = true)
  protected String memberCode;
  @XmlElement(required = true)
  protected String name;
  protected List<SubsystemType> subsystem;
  @XmlAttribute(name = "id")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlID
  @XmlSchemaType(name = "ID")
  protected String id;

  /**
   * Gets the value of the memberClass property.
   * 
   * @return possible object is {@link MemberClassType }
   * 
   */
  public MemberClassType getMemberClass() {
    return memberClass;
  }

  /**
   * Sets the value of the memberClass property.
   * 
   * @param value allowed object is {@link MemberClassType }
   * 
   */
  public void setMemberClass(MemberClassType value) {
    this.memberClass = value;
  }

  /**
   * Gets the value of the memberCode property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getMemberCode() {
    return memberCode;
  }

  /**
   * Sets the value of the memberCode property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setMemberCode(String value) {
    this.memberCode = value;
  }

  /**
   * Gets the value of the name property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the subsystem property.
   * 
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the subsystem property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * 
   * <pre>
     *    getSubsystem().add(newItem);
     * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list {@link SubsystemType }
   * 
   * 
   */
  public List<SubsystemType> getSubsystem() {
    if (subsystem == null) {
      subsystem = new ArrayList<SubsystemType>();
    }
    return this.subsystem;
  }

  /**
   * Gets the value of the id property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setId(String value) {
    this.id = value;
  }

}
