//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.15 at 05:50:29 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.riik.ee/schemas/deccontainer/vers_2_1/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ee.riik.schemas.deccontainer.vers_2_1;
