//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.05 at 11:54:11 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://x-road.eu/xsd/identifiers", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.x_road.xsd.identifiers;
