//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.29 at 02:39:43 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dhx.x-road.eu/producer", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.x_road.dhx.producer;
