//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.21 at 02:49:54 PM EEST 
//


package eu.x_road.dhx.producer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="memberCodes" type="{http://dhx.x-road.eu/producer}memberCodes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "memberCodes"
})
@XmlRootElement(name = "representationListResponse")
public class RepresentationListResponse {

    @XmlElement(required = true)
    protected MemberCodes memberCodes;

    /**
     * Gets the value of the memberCodes property.
     * 
     * @return
     *     possible object is
     *     {@link MemberCodes }
     *     
     */
    public MemberCodes getMemberCodes() {
        return memberCodes;
    }

    /**
     * Sets the value of the memberCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberCodes }
     *     
     */
    public void setMemberCodes(MemberCodes value) {
        this.memberCodes = value;
    }

}
