//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.13 at 05:49:27 PM EEST
//


package eu.x_road.dhx.producer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="members" type="{http://dhx.x-road.eu/producer}members"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "members"
})
@XmlRootElement(name = "representationListResponse")
public class RepresentationListResponse {

  @XmlElement(required = true)
  protected Members members;

  /**
   * Gets the value of the members property.
   * 
   * @return possible object is {@link Members }
   * 
   */
  public Members getMembers() {
    return members;
  }

  /**
   * Sets the value of the members property.
   * 
   * @param value allowed object is {@link Members }
   * 
   */
  public void setMembers(Members value) {
    this.members = value;
  }

}
